# Generated by Django 4.2.2 on 2023-06-10 07:19

from django.db import migrations, models
import tournament.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('osu_id', models.PositiveIntegerField(editable=False, unique=True)),
                ('osu_username', models.CharField(max_length=15, unique=True)),
                ('roles', tournament.models.UserRolesField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
