# Generated by Django 4.2.2 on 2023-06-15 04:39

from django.db import migrations
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_user_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=tournament.models.UserRolesField(default=0),
        ),
    ]
