# Generated by Django 4.2.2 on 2023-06-17 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mappool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', tournament.models.UserRolesField(default=0)),
                ('join_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=64)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamentbracket')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.PositiveSmallIntegerField()),
                ('starting_time', models.DateTimeField()),
                ('teams', models.ManyToManyField(to='tournament.tournamentteam')),
                ('tournament_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamentround')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentIteration',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('users', models.ManyToManyField(through='tournament.TournamentInvolvement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tournamentinvolvement',
            name='tournament_iteration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamentiteration'),
        ),
        migrations.AddField(
            model_name='tournamentinvolvement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='tournament_iteration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamentiteration'),
        ),
        migrations.CreateModel(
            name='MappoolBeatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatmap_id', models.PositiveSmallIntegerField()),
                ('modification', models.CharField(max_length=4)),
                ('artist', models.CharField()),
                ('title', models.CharField()),
                ('difficulty', models.CharField()),
                ('star_rating', models.FloatField()),
                ('overall_difficulty', models.FloatField()),
                ('approach_rate', models.FloatField()),
                ('circle_size', models.FloatField()),
                ('health_drain', models.FloatField()),
                ('cover', models.CharField()),
                ('mappool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.mappool')),
            ],
        ),
        migrations.AddField(
            model_name='mappool',
            name='tournament_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamentround'),
        ),
    ]
