# Generated by Django 4.2.2 on 2023-06-17 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_tournamentinvolvement_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappool',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mappool',
            name='tournament_round',
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='mappool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='tournament.mappool'),
            preserve_default=False,
        ),
    ]
