# Generated by Django 4.2.2 on 2023-06-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_remove_mappool_name_remove_mappool_tournament_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoolbeatmap',
            name='beatmap_id',
            field=models.PositiveIntegerField(),
        ),
    ]
