# Generated by Django 4.2.2 on 2023-06-20 05:16

from django.db import migrations, models
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_mappoolbeatmap_beatmap_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbracket',
            name='type',
            field=tournament.models.BracketTypeField(default=tournament.models.BracketType['DOUBLE_ELIMINATION']),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='bans',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='is_losers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='picks',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='wins',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='ban_order',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
