# Generated by Django 4.2.2 on 2023-06-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_tournamentbracket_type_tournamentmatch_bans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentround',
            name='full_name',
            field=models.CharField(default='none', max_length=32),
            preserve_default=False,
        ),
    ]
