# Generated by Django 4.2.2 on 2023-06-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_tournamentiteration_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentiteration',
            name='full_name',
            field=models.CharField(default='Offline Chat Tournament 3', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournamentiteration',
            name='name',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
