# Generated by Django 4.2.2 on 2023-06-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_tournamentiteration_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='osu_cover',
            field=models.CharField(default=''),
        ),
    ]
