# Generated by Django 4.2.2 on 2023-07-07 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentround',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 7, 1)),
            preserve_default=False,
        ),
    ]
