# Generated by Django 4.2.2 on 2023-07-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_tournamentiteration_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentiteration',
            name='links',
        ),
    ]
