# Generated by Django 4.2.2 on 2023-07-23 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0021_remove_tournamentteam_players_staticplayer"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticplayer",
            name="is_captain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staticplayer",
            name="tier",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="commentator1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="commentator2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="is_quals",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="referee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="streamer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tournamentmatch",
            name="starting_time",
            field=models.DateTimeField(null=True),
        ),
    ]
