# Generated by Django 4.2.2 on 2023-07-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0023_remove_tournamentmatch_is_quals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentmatch",
            name="osu_match_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="tournamentteam",
            name="team_icon",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
