# Generated by Django 4.2.2 on 2023-07-25 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0024_tournamentmatch_osu_match_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentteam",
            name="bracket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="tournament.tournamentbracket",
            ),
        ),
    ]
