# Generated by Django 4.2.2 on 2023-07-25 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0025_tournamentteam_bracket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentteam",
            name="bracket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="tournament.tournamentbracket",
            ),
        ),
    ]
