# Generated by Django 4.2.2 on 2023-07-25 03:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0026_alter_tournamentteam_bracket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournamentteam",
            old_name="team_icon",
            new_name="icon",
        ),
        migrations.RenameField(
            model_name="tournamentteam",
            old_name="team_name",
            new_name="name",
        ),
    ]
