# Generated by Django 4.2.2 on 2023-07-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0027_rename_team_icon_tournamentteam_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentteam",
            name="seed",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
