# Generated by Django 4.2.2 on 2023-08-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0028_tournamentteam_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentmatch",
            name="finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournamentmatch",
            name="team_order",
            field=models.CharField(default=""),
        ),
    ]
