# Generated by Django 4.2.2 on 2024-01-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0032_tournamentbracket_challonge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappool',
            name='mappack',
            field=models.CharField(default=''),
        ),
    ]
