# Generated by Django 4.2.2 on 2024-01-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0033_mappool_mappack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappool',
            name='mappack',
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='mappack',
            field=models.CharField(default=''),
        ),
    ]
